# Deploy demo service pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eater-app
spec:
  selector:
    matchLabels:
      app: eater-app
  template:
    metadata:
      labels:
        app: eater-app
    spec:
      containers:
        - name: eater-app
          image: eaterapp:latest
          imagePullPolicy: IfNotPresent          
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: # setting request and limit, we can use this to set utilization rate.
            requests: 
              cpu: 250m
              memory: 150Mi

---
apiVersion: v1
kind: Service
metadata:
  name: eater-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: eater-app
  type: ClusterIP